TRAIN:
    # Number of training epochs
    epochs: 90
    
    # Architecture name, see pytorch models package for
    # a list of possible architectures
    arch: 'resnet50'

    # Starting epoch
    start_epoch: 0

    # SGD paramters
    lr: 0.2
    momentum: 0.9
    weight_decay: 0.0001

    # Print frequency, is used for both training and testing
    print_freq: 10

    # Dataset mean and std used for data normalization
    mean: !!python/tuple [0.485, 0.456, 0.406]
    std: !!python/tuple [0.229, 0.224, 0.225]
    
ADV:
    defense_method: 'pgd' # ['pgd', 'free', 'random']

    # FGSM parameters during training
    clip_eps: 4.0
    fgsm_step: 4.0

    # Number of repeats for free adversarial training
    n_repeats: 4

    # PGD attack parameters used during validation
    # the same clip_eps as above is used for PGD
    pgd_attack: 
    - !!python/tuple [10, 0.00392156862] #[10 iters, 1.0/255.0]
    - !!python/tuple [50, 0.00392156862] #[50 iters, 1.0/255.0]

    # PGD training setings
    delta_init: 'zero' # ['zero', 'random']

    attack_iters: 2
    
DATA:
    # Number of data workers
    workers: 16

    # Training batch size
    batch_size: 512

    # Image Size
    img_size: 256

    # Crop Size for data augmentation
    crop_size: 224

    # Color value range
    max_color_value: 255.0

    